package com.dbt.model;

public enum ConfigEnum {
	
	SENDER_SHARD,
	SENDER_REALM,
	SENDER__ACC_NM,
	SENDER_PRIVATE_KEY,
	SENDER_PUBLIC_KEY,
	SENDER_SEC,
	SENDER_NANO,
	RECEIVER_SHARD,
	RECEIVER_REALM,
	RECEIVER_ACC_NM,
	RECEIVER_PRIVATE_KEY,
	RECEIVER_PUBLIC_KEY,
	RECEIVER_SEC,
	RECEIVER_NANO,
	FUNDER_SHARD,
	FUNDER_REALm,
	FUNDER_ACC_NM,
	FUNDER_PRIVATE_KEY,
	FUNDER_PUBLIC_KEY,
	FUNDER_SEC,
	FUNDER_NANO,
	SM_ID,
	SM_FILE_ID;

}
